#!/usr/bin/env ruby

$:.unshift File.expand_path("../../lib", __FILE__)

require "hc"
require "rest-client"
require "uri"
require "shellwords"
require "json"
require "ansi"
require "readline"

if !ARGV.first || !File.exists?(ARGV.first)
  puts "No hc profile configuration file given"
  puts "Usage: hc example.yml"
  exit 1
end

profile = Hc::Profile.open(ARGV.first)

begin
  profile.start!
rescue Interrupt
end

puts "[bye]"
exit 0
